# Generated by Django 4.0.3 on 2022-04-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('LID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('ASUS', 'ASUS'), ('Acer', 'Acer'), ('Apple', 'Apple')], max_length=20)),
                ('Description', models.TextField()),
                ('Series', models.CharField(max_length=50)),
                ('Brand', models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('ASUS', 'ASUS'), ('Acer', 'Acer'), ('Apple', 'Apple')], max_length=50)),
                ('Uses', models.CharField(choices=[('Home', 'Home'), ('Business', 'Business'), ('Gaming', 'Gaming'), ('Student', 'Student'), ('Premium', 'Premium')], max_length=50)),
                ('Screen_size', models.FloatField(choices=[(13.0, 13.0), (13.3, 13.3), (14.0, 14.0), (14.5, 14.5), (15.0, 15.0), (15.6, 15.6)])),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Memory_Type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR3', 'DDR3')], max_length=10)),
                ('Maximum_memory', models.IntegerField(choices=[(16, 16), (8, 8), (4, 4)])),
                ('Hard_Disk_Description', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('HDD+SSD', 'HDD+SSD')], max_length=10)),
                ('Graphic_Card_Description', models.CharField(max_length=20)),
                ('USB_3_port', models.IntegerField(default=2)),
                ('HDMI_Port', models.IntegerField(default=1)),
                ('Resolution', models.CharField(choices=[('1366 x 768', '1366 x 768'), ('1600 x 900', '1600 x 900'), ('1920 x 1080', '1920 x 1080'), ('2304×1440', '2304×1440')], max_length=25)),
                ('Processor_Type', models.CharField(choices=[('CORE i3', 'CORE i3'), ('CORE i5', 'CORE i5'), ('CORE i7', 'CORE i7')], max_length=8)),
                ('Processor_Speed', models.FloatField()),
                ('Audio_Details', models.CharField(default='Speakers , Headphones', max_length=20)),
                ('Operating_System', models.CharField(choices=[('Windows 11', 'Windows 11'), ('Windows 10', 'Windows 10'), ('Linux', 'Linux'), ('Mac OS', 'Mac OS')], max_length=30)),
                ('Battery_life', models.IntegerField(choices=[(15, 15), (12, 12), (10, 10), (8, 8), (4, 4)])),
                ('Connectivity_Type', models.CharField(default='Bluetooth , Wi-Fi', max_length=20)),
                ('Country', models.CharField(max_length=10)),
                ('Manufacturer', models.CharField(max_length=10)),
                ('Weight', models.FloatField()),
                ('seller', models.CharField(max_length=25)),
            ],
        ),
    ]
