# Generated by Django 4.0.3 on 2022-04-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_laptops_hard_drive_size_laptops_included_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='Image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
