# Generated by Django 4.0.3 on 2022-04-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_laptops_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='Image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
