# Generated by Django 4.0.3 on 2022-04-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_laptops_maximum_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('MID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(choices=[('Samsung', 'Samsung'), ('LG', 'LG'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('HP', 'HP'), ('Acer', 'Acer')], max_length=20)),
                ('Description', models.TextField()),
                ('Series', models.CharField(max_length=50)),
                ('Brand', models.CharField(choices=[('Samsung', 'Samsung'), ('LG', 'LG'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('HP', 'HP'), ('Acer', 'Acer')], max_length=50)),
                ('Uses', models.CharField(choices=[('Home', 'Home'), ('Business', 'Business'), ('Gaming', 'Gaming')], max_length=50)),
                ('Screen_size', models.FloatField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Refresh_rate', models.IntegerField(choices=[(120, 120), (90, 90), (75, 75), (60, 60)])),
                ('display_technology', models.CharField(choices=[('LED', 'LED'), ('LCD', 'LCD'), ('CRT', 'CRT'), ('OLED', 'OLED'), ('QLED', 'QLED')], max_length=30)),
                ('panel_type', models.CharField(max_length=50)),
                ('USB_3_port', models.IntegerField(default=2)),
                ('USB_2_port', models.IntegerField(default=1)),
                ('HDMI_Port', models.IntegerField(default=1)),
                ('Resolution', models.CharField(choices=[('1920 x 1080', '1920 x 1080'), ('2560 x 1440', '2560 x 1440'), ('3840 x 2160', '3840 x 2160'), ('1366 x 768', '1366 x 768'), ('1440 x 900', '1440 x 900'), ('1280 x 800', '1280 x 800'), ('3440 x 1440', '3440 x 1440')], max_length=25)),
                ('Connector_Type', models.CharField(choices=[('DVI', 'DVI'), ('HDMI', 'HDMI'), ('VGA', 'VGA')], max_length=20)),
                ('Country', models.CharField(max_length=10)),
                ('Manufacturer', models.CharField(max_length=10)),
                ('Weight', models.FloatField()),
                ('seller', models.CharField(max_length=25)),
                ('Image', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
    ]
