# Generated by Django 4.0.3 on 2022-04-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_monitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitors',
            name='HDMI_Port',
        ),
        migrations.AlterField(
            model_name='laptops',
            name='Image',
            field=models.ImageField(null=True, upload_to='pics/laptops'),
        ),
        migrations.AlterField(
            model_name='monitors',
            name='Image',
            field=models.ImageField(null=True, upload_to='pics/monitors'),
        ),
    ]
