# Generated by Django 4.0.3 on 2022-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_monitors_hdmi_port_alter_laptops_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(choices=[('cannon', 'cannon'), ('HP', 'HP'), ('EPSON', 'EPSON')], max_length=20)),
                ('Description', models.TextField()),
                ('Series', models.CharField(max_length=50)),
                ('Brand', models.CharField(choices=[('cannon', 'cannon'), ('HP', 'HP'), ('EPSON', 'EPSON')], max_length=50)),
                ('Uses', models.CharField(choices=[('Home/office', 'Home/office'), ('A3 printers', 'A3 printers'), ('Laser pritners', 'Laser printers')], max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('printing_technology', models.CharField(max_length=30)),
                ('printer_function', models.CharField(choices=[('print,scan and copy', 'print,scan and copy'), ('pritn only', 'print only')], max_length=30)),
                ('Operating_System', models.CharField(default='windows', max_length=50)),
                ('printer_output', models.CharField(default='color', max_length=20)),
                ('sheet_size', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A3/A4/A5/A6', 'A3/A4/A5/A')], max_length=20)),
                ('Connector_Type', models.CharField(choices=[('USB', 'USB'), ('WiFi', 'WiFi'), ('USB + WiFi', 'USB + WiFi')], max_length=20)),
                ('Country', models.CharField(max_length=10)),
                ('Manufacturer', models.CharField(max_length=10)),
                ('Weight', models.FloatField()),
                ('seller', models.CharField(max_length=25)),
                ('Image', models.ImageField(null=True, upload_to='pics/monitors')),
            ],
        ),
        migrations.AlterField(
            model_name='monitors',
            name='Connector_Type',
            field=models.CharField(choices=[('DVI', 'DVI'), ('HDMI', 'HDMI'), ('VGA', 'VGA'), ('HDMI+VGA', 'HDMI+VGA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monitors',
            name='Refresh_rate',
            field=models.IntegerField(choices=[(144, 144), (120, 120), (90, 90), (75, 75), (60, 60)]),
        ),
    ]
