# Generated by Django 4.0.3 on 2022-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_printers_alter_monitors_connector_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='Image',
            field=models.ImageField(null=True, upload_to='pics/printers'),
        ),
    ]
