# Generated by Django 4.0.3 on 2022-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_printers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('HID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(choices=[('JBL', 'JBL'), ('BoAt', 'BoAt'), ('Sony', 'Sony'), ('Realme', 'Realme'), ('Apple', 'Apple')], max_length=20)),
                ('Description', models.TextField()),
                ('Series', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('Brand', models.CharField(choices=[('JBL', 'JBL'), ('BoAt', 'BoAt'), ('Sony', 'Sony'), ('Realme', 'Realme'), ('Apple', 'Apple')], max_length=50)),
                ('Category', models.CharField(choices=[('Wired', 'Wired'), ('Wireless', 'Wireless'), ('Earbuds', 'Earbuds')], max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Ear_placement', models.CharField(choices=[('In Ear', 'In Ear'), ('On Ear', 'On Ear'), ('Over Ear', 'Over Ear')], max_length=20)),
                ('Microphone', models.CharField(choices=[('yes', 'yes'), ('No', 'No')], max_length=10)),
                ('Connector_Type', models.CharField(choices=[('Wired', 'Wired'), ('Wireless', 'Wireless'), ('Earbuds', 'Earbuds')], max_length=20)),
                ('Compitible_device', models.CharField(default='Audio Player , Laptop, Mobile, Tablet', max_length=30)),
                ('Country', models.CharField(max_length=10)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('Weight', models.FloatField()),
                ('seller', models.CharField(max_length=25)),
                ('Image', models.ImageField(null=True, upload_to='pics/headphones')),
            ],
        ),
        migrations.AlterField(
            model_name='printers',
            name='Manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='printers',
            name='Uses',
            field=models.CharField(choices=[('Home/office', 'Home/office'), ('A3 printers', 'A3 printers'), ('Laser printers', 'Laser printers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='printers',
            name='sheet_size',
            field=models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A3/A4/A5/A6', 'A3/A4/A5/A6')], max_length=30),
        ),
    ]
