# Generated by Django 4.0.3 on 2022-04-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_customer_alter_headphones_compitible_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zinpcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
