# Generated by Django 4.0.3 on 2022-04-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_customer_zinpcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zinpcode',
            new_name='zipcode',
        ),
    ]
