# Generated by Django 4.0.3 on 2022-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_cart_product_cart_category_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='product',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='category',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
